### ISSUE TITLE
ERC20 Contract example - no checks on transferFrom()

### ISSUE THREAD

**Issue by ssteiger** [ethereum/vyper#1237]
### Version Information
--
### What's your issue about?

The example contract at:
https://github.com/ethereum/vyper/blob/master/examples/tokens/ERC20.vy
In line 74.

No checks are performed in the `transferFrom()` function.
I am not sure but couldn't anyone just pass any `from/to` address combination and effectively steal their funds?
Doesn't there need to be some check if the `_from` account has authorized the sender?

### How can it be fixed?

Option 1: Add something like this: 
`assert _from == msg.sender`

Option 2: Make the function `@private`

Option 3: Add something like this:
`assert self.allowances[_to][msg.sender] >= _value`
`self.allowances[_to][msg.sender] -= _value`

Option 4: Both option 1 and option 2

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/10925195/52504900-1c616f80-2bea-11e9-8551-b68369d7615d.png)

**Comment by fubuloubu** [comment]
So, this is a subtle thing. Option 3 basically already occurs.

In this line:
https://github.com/ethereum/vyper/blob/master/examples/tokens/ERC20.vy#L85

We are decrementing the sender's allowance as allocated by `_from`. If that allowance is lower than the amount we want to transfer, the function will revert (because we bake in SafeMath by default).

Should add a comment there to that effect (and also to `transfer`)

**Comment by jacqueswww** [comment]
Closing as this was merged.
