### ISSUE TITLE
Need of multiplatform support

### ISSUE THREAD

**Issue by ironexmaiden** [ethereum/vyper#1321]
## Simple Summary
@Vyper_Dev_Team is there any plan to convert vyper to a multi-platform language that will not only support ethereum protocol but also other such as tezos, neo, eos and others. The boost of this achievement will have a great impact on smart contract developing for developers who want to import a smart contract to multiple protocols

**Comment by fubuloubu** [comment]
No, there is no plan for that, but you are of course welcome to maintain a fork of Vyper with a backend for any platform of your choosing. It's open source software under MIT license.

**Comment by ironexmaiden** [comment]
@fubuloubu to be honest I didn't realize that vyper was an official ethereum language when I have post this issue I saw with suprise this fact thats why I had closed the issue immediately

**Comment by fubuloubu** [comment]
No problem! I just want you to feel welcome to fork and make use of the work we're doing in developing a language that is purpose-built for the domain of smart contract programming. I personally believe this is the way to go, and I hope Vyper will be an important language however this all plays out. I do not believe adapting general purpose programming langauges is the way to go (like how EOS and NEO enable smart contracts), so I at least encourage an exploration of what is possible with what we have developed (similar to Tezos, I think)

**Comment by ironexmaiden** [comment]
@fubuloubu Thank you for your encouragement Do you believe that a general purpose language will help DApp Devs? I think that the best approach is to create an abstract upper layer (like QT framework) on vyper and make an implementation on NEO which supports python also and EOS which supports C/C++, what's your opinion?

**Comment by fubuloubu** [comment]
No, I really don't think so. It is much more difficult to analyze the security of a general purpose programming language that has blockchain concepts available as add-on libraries instead of first-class citizens, especially languages as complex as python or C++.

Tezos is exceptional in that a DSL of OCaml is specified, which means they avoid the general purpose design problem and add specific constructs required for a blockchain environment.

Sorry, hut we should chat offline about this issue if you still have questions. We are far outside the scope of what GitHub issues are used for. I am on gitter.

**Comment by ironexmaiden** [comment]
@fubuloubu I have already found you on gitter,
