### ISSUE TITLE
Frequent use of CALLDATACOPY

### ISSUE THREAD

**Issue by Pet3ris** [ethereum/vyper#1381]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b9
* OS: osx 10.14.3
* Python Version: 3.7.2
* Environment (output of `pip freeze`):

### What's your issue about?

With this simple contract:

```python
@public
def __init__():
    pass

@public
def action(a: uint256):
    assert a > 10
```

The compiled bytecode has this set of blocks:

![image](https://user-images.githubusercontent.com/224585/55492842-cf20dd80-562f-11e9-90da-8cfcff0a0376.png)

Note the use of `CALLDATACOPY` followed by `MLOAD` which could be replaced with a single `CALLDATALOAD`. This would result in gas savings for the `MLOAD` and multiple `PUSH` statements.

(Please let me know in case I'm being annoying with these.)

### How can it be fixed?

Replace with `CALLDATALOAD` for simple function arguments.

**Comment by jacqueswww** [comment]
I think this is a perfect case for extending our VariableRecord logic (adding location=calldata) - which currently assumes everything is stored in a memory slots, especially because our input/call variables are immutable - no reason to do unnecessary copying.

@Pet3ris please keep them coming, always great to optimise things :)

**Comment by jacqueswww** [comment]
cc @charles-cooper I think you'll like this optimisation :)

**Comment by jacqueswww** [comment]
Note: Depends of merge of #1370
