### ISSUE TITLE
Fix voting example

### ISSUE THREAD

**Issue by DustinWehr** [ethereum/vyper#370]
### What's your issue about?
The problem is described here https://github.com/ethereum/viper/pull/302#issuecomment-326341764

### How can it be fixed?

I'm happy to help if @DavidKnott and @fubuloubu don't have the time.

3 options, all of which still need some scrutiny:
* @fubuloubu sketched a fix in two comments: [this change](https://github.com/ethereum/viper/pull/302#issuecomment-326353960) alone seemed like it'd work, but the resulting program is more restricted than the Solidity example.  [The second comment](https://github.com/ethereum/viper/pull/302#issuecomment-326357970) is about addressing that restriction. 
* [I wrote one](https://gist.github.com/DustinWehr/b4f3e0d3b1d29a55f4c3042e0485bd69) that differs more from @DavidKnott's.
* [More complex version of the previous](https://gist.github.com/DustinWehr/d178b3a0b50dcb217a26ad1f26be82e1), including a cycle breaking capability.

**Comment by fubuloubu** [comment]
I think in general the examples don't need to be fully realized, production code. Their point is more to show how much simpler and clearer Viper syntax is as examples on how to get started.

That being said, replicating some Solidity examples is important as a comparison.

I didn't get a chance to look too deeply at what you did, but keep that in mind.

**Comment by DavidKnott** [comment]
@DustinWehr It'd be great if you made a PR.  I second what @fubuloubu mentioned, it's a lot more important for people to understand examples and the viper syntax used then to have them be fully functionally.  Maybe you could make a pr with 2 voting examples a simple one and your more complex /  feature complete one?

**Comment by DavidKnott** [comment]
@DustinWehr Are you working on this, if not I can do it this week.

**Comment by DustinWehr** [comment]
I never did get running tests working on my system... Can you run them (the existing test) on this before I submit a PR? 
https://gist.github.com/DustinWehr/98c9310afab793588aa8e031f1d79aec

**Comment by fubuloubu** [comment]
@DustinWehr I think you need a clearer example of what you're suggesting for `assert`, probably in a different issue. I sort of like the `require`/`assert` thing in solidity (like maybe 80% like it lol). In solidity, `require` means front end assumptions about inputs, and `assert` means the backend of calculations executed correctly. Your suggestion of `should` actually sounds like a great candidate for what you are describing in (1), but I don't really follow exactly what you mean there (e.g. `should` describes a scenario that can potentially be optimized away assuming formal correctness is verified for that contract).

In my (old) industry, we wrote requirements documents that had different types of requirements with different assumptions on implementation. `shall` was different than `will` or `should`. It's interesting to think of them as all essentially `assert` under the hood, but with different semantic contexts designed to help the auditor/reader understand the assumptions present.

**Comment by DustinWehr** [comment]
Oh! How embarrassing... Thanks @fubuloubu. As you must have guessed, Viper is my first smart contract language; otherwise I would not have suggested inconsistent names. I'll open a more-thorough issue about it later.

A quick response to your comments though: So `require` is (2) and `assert` is (3).
You understood what I meant by (1) (now `should`): `should A` means you believe that whenever the computation reaches that statement, `A` evaluates to true (and I forgot to mention A is side effect free). So it's something that should be provable. The compiler would ignores `should` statements, but a Viper interpreter (e.g. the python test runner) would stop immediately if the statement is false.

**Comment by fubuloubu** [comment]
Your suggestion for `should` sort of sounds like a [Theorem Prover](https://en.wikipedia.org/wiki/Automated_theorem_proving). Like, you suggest putting `should A` statements in your code to assert some invariant that should never be false if the system is designed correctly?

Typically, theorem provers work as having a separate model representing your intention as it's own system (aka a collection of requirements called "theorems" about your system's properties). You then take that system and formalize it to create a set of test cases showing all possible scenarios describing your system. Those test cases are run against the actual system to prove formal correctness of your system during actual operation (in this case, EVM Bytecode actually running on the EVM).

This is all part of the realm of Formal Verification, which is a very interesting subject (I took a course my last year in grad school). Ethereum/Smart Contract systems are a great application for this field of academic study both because it is so important to get the system to be provably correct, and because the smart contracts we create are actually pretty high-level and lend themselves well to being theorized against using these techniques. @pirapira is very active in this space. He has some musings you can read about [here](https://github.com/pirapira/ethereum-formal-verification-overview).

It would be an awesome feature for Viper to implement something in this regard, and probably speed along it's adoption (over Solidity). A few theorem provers out there can target Python (check out [Z3 Prover](https://github.com/Z3Prover/z3)), and since we're still operating on a subset of Python syntax (@DavidKnott, one reason to KEEP the Python AST), perhaps there might be an easy way to integrate this into the Viper compiler. It certainly is a big ask, but I think it is a big reward item.

I hope that isn't TMI lol

**Comment by DustinWehr** [comment]
Not TMI. Formal Verification is a major part of my work with [Legalese](https://legalese.com). Our computational legal contracts will compile to EVM bytecode, probably via Viper. We expect to be in contact with Yoichi in the near future (if Virgil isn't already).

**Comment by fubuloubu** [comment]
@DustinWehr Very cool! Do you know/have experience with FV for Python? That post just got me thinking a little bit, and I think the current syntax of Viper can probably support any tool that was developed for Python without a large amount of modifications.

**Comment by fubuloubu** [comment]
P.S. I love the faux newspaper aesthetic to Legalese's website!

**Comment by pirapira** [comment]
Meaow, meaow.

**Comment by DavidKnott** [comment]
I'm looking into formal verification now, as @fubuloubu mentioned because we're using python syntax there are a bunch of cool tools at our fingertips :)

**Comment by fubuloubu** [comment]
Actually less tools then I thought, but there are some. I was thinking about a Bounded Model Checker

**Comment by DustinWehr** [comment]
This sounds like the right path as far as programmer interface: https://www.reddit.com/r/ethdev/comments/737jik/anyone_experince_to_use_formal_specifications_eg/dnor1tp/?context=3

The lack of (unbounded) loops and recursion in Viper should be a _huge_ benefit for FV.

**Comment by DustinWehr** [comment]
@DavidKnott the OSX instructions say `make install` but the Makefile appears to (I don't know make) require `make init`

**Comment by DustinWehr** [comment]
Ok with you guys if I change the meaning of the `weight` field, so it satisfies this invariant?
(sum of `weight` over all voters) + (sum of `vote_count` over all proposals) = `voter_count` 

This requires changing one of the test cases.
The Solidity example doesn't do this (i.e. never sets a voter's `weight` to 0 after counting it), because it's not necessary, but I think that's kind of counterintuitive.

Also, a question: is the address `0x0000000000000000000000000000000000000000` falsey, and is it the only falsey address?

**Comment by fubuloubu** [comment]
Not sure I quite follow, but the invariant should be like "the overall amount of votes available (whether used or not) stays the same"

It would be cool as a way to define your own generated test cases in the source. Hmm....

**Comment by DavidKnott** [comment]
Closing as the voting example has been fixed, thanks again @DustinWehr
