### ISSUE TITLE
Suggestion: add Solidity-like directive with compiler/language version

### ISSUE THREAD

**Issue by federicobond** [ethereum/vyper#456]
A directive with the Viper version of a source file can help migrate code to newer versions and introduce or change functionality more smoothly.

A possible, backward-compatible solution is to introduce directives inside comments:

```python
# pragma viper: ^0.0.2
```

#### Cute Animal Picture

![6f09da0ba08cc20f2d5f80245e5db75a](https://user-images.githubusercontent.com/138426/32642058-8498f18c-c5b0-11e7-8705-279c9401b755.jpg)

**Comment by fubuloubu** [comment]
Agree with poster, we need a way to determine compiler versions of deployed contracts.

Might I suggest an alternative though, that the viper compiler automagically adds a 'viper_version() -> bytesN` method returning the version of Viper the deployed contract was created with, so that 1. Developers don't have to maintain magic pragma numbers and 2. Provide a reliable way to query for this info from Deployed contracts (versus relying on published source code).

In addition this, I've had day dreams of how Viper might also add a standard method that returns the ABI (instead of having to copy that down) and maybe even someday provide a robust method that Viper can sign deployed contracts as created by a specific version, something like a cryptographic checksum of the compiler signing a checksum of the Bytecode or something along those lines.

It always seemed crazy to me some of the oddities that Solidity makes you deal with.

**Comment by federicobond** [comment]
I think we are targetting two different use cases. Versioning the source code serves a different purpose than having a magic number in the deployed bytecode.

By requiring/encouraging users to declare a language version in their sources, language implementers have more freedom to change the syntax or semantics of the language while providing users with a clear migration path. For example, users can also opt-in to experimental features that are not available in the stable versions, or can stick to some old behavior if they don't have time to update their contracts to the latest features. When the compiler finds code that has an old version declared, it can emit warnings that help users migrate their code. Tooling can also take advantage of this information to select an appropriate parser or provide better suggestions.

**Comment by fubuloubu** [comment]
Well, what I mean is that when you decide to target a specific version of solidity via the pragma, you still have to download and maintain that older version of solc in order to compile it. The only difference in having an explicit line in the source code describing your version is that solc barfs if you try to compile with a different version.

My suggestion is slightly different. I am of the opinion that I don't care what version of solidity you said you used to compile a program, I want to know what version you ACTUALLY used to compile a deployed program as that is more important to an auditor to replicate it. You could argue that the pragma directive acheives this, but I'd rather have the compiler sign it somehow.

I think there's a place for both suggestions, having the compiler alert you if you're not using the right version you asked for is definitely a useful feature. I respectful disagree with the sentiment that this enables any more freedom on the Viper developer's part; basically you will use whatever version of Viper you feel comfortable with. But yes, having a clear upgrade/migration path (major/minor/patch versions) will be necessary beginning with our beta.

**Comment by jacqueswww** [comment]
+1 that we will need to do this the moment we go into beta (actually publishing releases).

**Comment by federicobond** [comment]
> I want to know what version you ACTUALLY used to compile a deployed program as that is more important to an auditor to replicate it.

A worthy goal, but that's not what the pragma is for. The pragma should not declare a specific version, but a compatibility target. This lets you warn users compiling old contracts of potential pitfalls when updating their code to the latest version of Viper and even retaining old behavior for a while to ease migration.

**Comment by fubuloubu** [comment]
Okay, I see what you're saying. As a sort of aside, I'm from the school of thought that you should copy, never reuse, code. The intention is that you copy code as a starting point for replicating a certain behavior, but never trust that you're getting that behavior until it's tested to your own satisfaction. If you have a test suite or FV model that worked for that original code module, it should still work with a newer compiler version (assuming that version retained all the same features you cared about). This ethos sort of informs my understanding around what I want to see Viper end up as, and I think with it's emphasis on copy patterns vs reuse patterns (e.g. disallowing inheritance, modifiers, etc.), my understanding is compatible with Viper's vision.

I definitely want more conversation about this though. I think the biggest part of designing a new programming language isn't what features to design but what the spirit of the endevour actually is, and that takes all of us together.

**Comment by federicobond** [comment]
Fair enough. I would love to see how those principles play out in real-world examples and hopefully enrich the whole smart contract ecosystem.

**Comment by jacqueswww** [comment]
Pragma tag was added for the beta.
