### ISSUE TITLE
No check when a function expects a return value

### ISSUE THREAD

**Issue by yzhang90** [ethereum/vyper#515]
### What's your issue about?
Compiler should reject the following program
```
y: num[3]

@public
def foo(x: num[3]) -> num:
    self.y = x
```
because `foo` expects a return value of type `num`, however the current compiler still compiles.

### How can it be fixed?

Need to keep track of the return type of each branch.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/33245094-af16df58-d2c8-11e7-8ebd-84e824e426a2.png)

**Comment by fubuloubu** [comment]
If you don't specify, it probably returns the null case, or 0 for `num`.

You're correct though, you should have some return statement if your function returns.

**Comment by fubuloubu** [comment]
This is actually an interesting Formal Verification problem, for methods with lots of branches, is there a branch that does not return a value?

**Comment by DavidKnott** [comment]
It gets even more fun if we force all branches to end in `return` or a `throw` 😄

**Comment by fubuloubu** [comment]
Well, the easiest way to start is to just `throw` if no return value is set by end of execution. That solves this scenario easily.

But for future Formal Verification, we would implement a routine to check the program branches all contain a return statement and catch it at compile time instead of during runtime, as the above solution would provide (basically allowing us to remove the extra bytecode to account for this issue)

**Comment by jacqueswww** [comment]
Closing in favour of https://github.com/ethereum/vyper/issues/590
