### ISSUE TITLE
Line numbers on readthedocs don't match up with the code as on Github

### ISSUE THREAD

**Issue by jamesray1** [ethereum/vyper#579]
![screenshot from 2017-12-12 15-14-51](https://user-images.githubusercontent.com/16969914/33867218-382d76f2-df4f-11e7-8307-e79d6a8edbfd.png)

![screenshot from 2017-12-12 15-18-23](https://user-images.githubusercontent.com/16969914/33867276-b866305c-df4f-11e7-8740-243060f02905.png)

#### Cute Animal Picture

![screenshot from 2017-12-12 15-16-31](https://user-images.githubusercontent.com/16969914/33867239-742c8792-df4f-11e7-9c2b-fbd59baee847.png)

**Comment by blaisep** [comment]
@jamesray1 I think you might be looking at a different commit from the one used on readthedocs.
readthedocs used commit `9be6289d733e940c6552cb1352d316a479a392f0`
and in _that_commit `def finalize():` appears on line 28.
The code in `docs/viper-by-example.rst` specifies:
```
.. literalinclude:: ../examples/crowdfund.v.py
  :language: python
  :lines: 24-27
```
So a quick fix would be to update  `docs/viper-by-example.rst` to say:
```
.. literalinclude:: ../examples/crowdfund.v.py
  :language: python
  :lines: 28-31
```

**Comment by fubuloubu** [comment]
@blaisep can you explain "include text in docstrings" for the uninitiated? (e.g. myself lol)

**Comment by blaisep** [comment]
@fubuloubu For example, if we look at the rst source for:
http://docs.python-requests.org/en/master/api/#requests.request
in the file:
https://github.com/requests/requests/blob/master/docs/api.rst , notice that the section describing the `requests.request` function is not filled out in detail. All that appears in the rST source is: 
```
.. autofunction:: request
```

So the description of `requests.request` appears in https://github.com/requests/requests/blob/master/requests/api.py#L17 . Also, the HTML output makes use of the Sphinx `viewcode` extension : http://www.sphinx-doc.org/en/stable/ext/viewcode.html 
So if you're reading the doc and you want to read the python code, click on the link called _source_ and it displays the relevant section of the `.py` file. Sphinx resolves the line numbers and HTML refs when the docs get built.

**Comment by sguberman** [comment]
I think there are two issues here:

- The original issue raised by @jamesray1
    - When viewed on readthedocs, the line *spacing* does not match between the line numbers on the left and the lines of code on the right.
- Another issue found by @blaisep
    - The sections of code shown in the explanations are truncated because the line numbers in the .rst doc are not correct. These need to be kept in sync when the source files are updated, perhaps automatically.

I am a newbie to contributing to open source. For now, I would be willing to tackle the temporary fix suggested by @blaisep and at least call out the correct lines in the vyper-by-example.rst file. But I am not sure about how to correct the first issue, it might be a problem with the template being used?

**Comment by fubuloubu** [comment]
@sguberman let us know what you find! Welcome to open source!

**Comment by blaisep** [comment]
Nice catch, @guberman , in Sphinx the term template refers to the Jinja
scripts used to compose the content of the HTML page and the term "theme"
refers to the collection of templates, CSS and JavaScript coordinating the
overall appearance of the HTML.

When I run into a discrepancy between a local build and a readthedocs
build, it is often because I have specified  `theme = sphinx_rtd` in my
conf.py and it conflicts with the `sphinx_rtd` theme used on the server.

IMHO, if we don't need anything special, omit the template variable in
conf.py and let the server use its default readthedocs theme.

PM me for more context.
Blaise

**Comment by sguberman** [comment]
Submitted pull request #692 to address the incorrect line references in the code examples.

**Comment by sguberman** [comment]
Did some digging on the the sphinx theme as @blaisep suggested. There seems to be a bug in the sphinx template itself: [Issue 417](https://github.com/rtfd/sphinx_rtd_theme/issues/417)

Let me see if removing the template from `conf.py` and using the server-side RTD default fixes the problem.

**Comment by sguberman** [comment]
Removing the theme in `conf.py` fixed the problem on my local machine, but unfortunately not on RTD. I think maybe they are overriding whatever theme is chosen in `conf.py`. Since this particular line spacing issue is supposedly fixed in v2.5 it might be better to wait for that release of the theme and see if it helps. Open to suggestions here, but in the meantime I still think it would be beneficial to merge in #692  to at least show the correct code in the correct places.

**Comment by fubuloubu** [comment]
Totally, treat them separately

**Comment by jacqueswww** [comment]
@fubuloubu can I close this issue?

**Comment by fubuloubu** [comment]
#692 got merged in an attempt to fix this. Will have to audit the updates against this issue
