### ISSUE TITLE
Convert num(sec) to num

### ISSUE THREAD

**Issue by khotkevych** [ethereum/vyper#591]
I want to use the block.timestamp in an arithmetic expression for arrays index calculation.
Let's jump straight into the example:

`arr : num[2]`

`@public`
`def test(): `
`self.arr[block.timestamp %2 ] = 1`

I've got an error: `Cannot use positional values as modulus arguments!`

Ok. Let's try something different: 

`arr : num[2]`
`tmp : timestamp`

`@public`
`def test(): `
`self.tmp = 0`
`self.arr[(block.timestamp - self.tmp)%2] = 1`

Now I see: `Typecasting from base type num(sec) to num unavailable`

Actually, there is a way to do what I want:

`arr : num[2]`
`tmp : timestamp`

`@public`
`def test(): `
`self.tmp = 0`
`some_var = (block.timestamp - self.tmp)%2`
`if some_var == 0:`
`self.arr[0] = 1` 
`else:`
`self.arr[1] = 1` 

Could you please clarify me the positional value restriction?

And is there any way to solve my problem more humane way?

* viper Version: 0.0.2

**Comment by fubuloubu** [comment]
The basic problem is the `num(sec)` to `num` thing (as noted), or to rephrase, you are trying to use the result of a mathematical expression in one set of units (e.g. `sec`) to another (no units). I think in your circumstance, using the result as an array index, we should probably not care about which units the index is in when it's being used.

I don't think we had ever thought about this scenario. Perhaps the fact that math is being done inside the array indexing operator may be the source of the issue. Please try `self.arr[some_var] = 1` (instead of the `if` statement) in your last example to confirm that theory. It's probably the units of the index thing though.

**Comment by fubuloubu** [comment]
Also, the "postional value" message is pretty unclear to me too

**Comment by khotkevych** [comment]
@fubuloubu 
`self.arr[some_var] = 1` 
has the same error
`Typecasting from base type num(sec) to num unavailable`

**Comment by DavidKnott** [comment]
Hmmm, seems like the simplest solution is to allow positional units as array indexes, though I think this issue is a symptom of a bigger problem, units in Viper are generally quite clunky.

**Comment by fubuloubu** [comment]
@DavidKnott agree on both those points. I think it is okay to allow this behavior for now, there's no reason in my mind to disallow using a num of a specific unit for an index (as long as the index is in the right range)

**Comment by yzhang90** [comment]
I think it is better introduce some builtin function to get the pure value of a variable by dropping the units.

**Comment by DavidKnott** [comment]
@khotkevych Sorry for not thinking of this right away.  You should use the `as_unitless_number` built in function
```
arr: num[2]
@public
def foo() -> num:
    x = as_unitless_number(block.timestamp) % 2
    return self.arr[x]
```

**Comment by jacqueswww** [comment]
Closing, `as_unitless_number` is the answer.
