### ISSUE TITLE
Limit map key size 

### ISSUE THREAD

**Issue by yzhang90** [ethereum/vyper#637]
### What's your issue about?
1. In vyper compiler, the key_type of map can only be base type and byte array type, which is inconsistent with the doc(https://github.com/ethereum/vyper/blob/master/docs/types.rst) : "Here _KeyType can be almost any type except for mappings, a contract, or a struct".

2. Assume key type can only be base type and byte array type. I can have the following program:
```
a:num[bytes<=100000]
@public
def __init__():
    self.a["absssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"] = 1
    pass
```
will cause the compiler to throw an error "Can't have a zerovalent argument to an opcode or a pseudo-opcode! seq", which is weird.

### How can it be fixed?

Since the storage is limited, it's better to restrict the size of the key of the map.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/5641590/35161380-a92d46f6-fd05-11e7-9148-846a24becb14.png)

**Comment by jacqueswww** [comment]
@yzhang90 thanks for the report.
Having a look now.

**Comment by jacqueswww** [comment]
@DavidKnott @fubuloubu @yzhang90 Ok I have investigated this, there was a fault in the way we did the sha3 accross the key bytearray. I have now fixed it that any size can work (any size larger than 32 would've  caused trouble).

Now the question:
Do we want to limit the key size?

**Comment by DavidKnott** [comment]
I think we should let people use any sized key.  The downside is gas costs and people should be able to choose whether or not those are worth it themselves.  Can you guys think of situations where someone would need to use more than 32 bytes as a key?

**Comment by fubuloubu** [comment]
Not offhand. Mapping structs maybe.

I was discussing with @jacqueswww in the Gitter, I think it we should not enable larger keys by default. The writer has the option of using it via `my_mapping[sha3(A, B, ...)]`, which would be accepting the costs of this decision explicitly. Personally, I also don't like extended key sizes as it it increases the vector for a key collision attack (finding another set of objects `A, B, ...` that overwrite the key in the hashmap), which is a possibility[1](https://eprint.iacr.org/2012/672.pdf), and the risk increases when data over the key size is used. This might be paranoia, because the attack is still very difficult, but it seems like a lot of concerns for what I currently believe has little utility in practice.

Anyways, we'd have to come up with a practical limit for the amount of data that can be used to generate a key in the hashmap. How would we choose that limit?

**Comment by DavidKnott** [comment]
I don't mind limiting it and making it explicit, but if we've got to worry about keccak256 collisions we've got bigger problems 😄.

**Comment by fubuloubu** [comment]
True, but consider this: other uses of keccak (such as a block hashing) avoid any sort of attack because not only it is very difficult to compute a reverse hash that has the right properties, but you have a limited time to do it in (e.g. 6+ confirmations in PoW is effectively final), or it is very expensive if you are discovered making the change (high cost plus multiple validators in PoS) and many other parties have copies to compare against.

In this scenario, imagine someone wrote something like this: `token_balance[sha3(owner: address, acct: uint256)]`. Then they could sit there and look at two addresses that, when concated together, gives the desired key hash and allows the attacker to take simply control of funds. This attack is still extremely expensive and impractical for some set of keysizes, but if successful there is nothing else preventing the attack from being successful. The attack surface becomes easier as the keysize is increased, in this scenario there is likely a 2nd key corresponding to completely different choices of `address` and `uint256` that map to the same hash. The paper I linked in my prior post takes 2**115 iterations to find a collision in a key space of 1600 bits (If I am reading that correctly).

I'm no expert by any means in cryptographic hashes, but that part makes sense to me: you have increased chances of finding a collision for every multiple of the base keysize used for the hashmap. And with no other effective means of securing against that attack (anyone can submit transactions to a smart contract), limiting that as a default enabled feature makes sense to me because base keysize (256bit) has the smallest attack surface possible.

**Comment by jacqueswww** [comment]
@DavidKnott @yzhang90 @fubuloubu can we agree on a fixed size limit for a bytes key? I say 1024.
