### ISSUE TITLE
Only allow one function call in assignment expressions

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#671]
### What's your issue about?

An expression should only allow constant expression to be used.

```python
x: decimal

@constant
@private
def a () -> num:
    return 1

@private
def b () -> num:
    self.x = 333.33
    return 2

@public
def test():
    a: num = 3 * self.a()  # allowed
    b: num = self.a() or 4 * self.b()  # not allowed 
```

### How can it be fixed?

Let's discuss any downsides, and then implement it.

#### Cute Animal Picture

![](http://www.dogster.com/wp-content/uploads/2017/03/shutterstock_puppy_paws_thumb.jpeg)

**Comment by fubuloubu** [comment]
I don't think there's necessarily a problem having one state changing function call another, so I choose to interpret this as one state changing function calling another that returns stuff.

I think in general, we should move to discouraging returns from state changing functions in order to stop design patterns from developing around this poor practice (in my opinion). This looks like a great corner case for that paradigm, so I agree with this issue given that context.

I sort of picture "returns" for a state changing function (from a usage perspective) being receipts, which match the asynchronous nature of transactions in Ethereum.

**Comment by jacqueswww** [comment]
As discussed on the PR. Makes sense to only address `a = self.a() or self.b()` scenarios I have update the issue accordingly.
