### ISSUE TITLE
Vyper example with web3py / web3

### ISSUE THREAD

**Issue by PaulSka** [ethereum/vyper#912]
Hi,

Can you provide examples (present on examples folder or online compiler) with web3py or web3 library ?
It's very usefull for starting with Vyper and Ethereum.

For example, with simple_open_auction.vy :

* How to initialize smart contract ?
* How to send transaction for transfert
* ...

Thanks you.

#### Cute Animal Picture

![d9505f570a73f1c4e290ecf00b250f0e--baby-kittens-small-kittens](https://user-images.githubusercontent.com/1415425/41600100-4509f902-73d5-11e8-926b-c3864fc318f6.jpg)

**Comment by fubuloubu** [comment]
Good idea!

**Comment by gakonst** [comment]
I've written a minor wrapper/helper around web3.js for Vyper. You may find it helpful https://github.com/gakonst/VyperWeb3Deploy.

Tbh the process isn't different from Solidity, you just compile (with `vyper` instead of `solc`) to get the ABI, create a new contract object, deploy it and interact with it as usual.

**Comment by jacqueswww** [comment]
https://vyper.readthedocs.io/en/v0.1.0-beta.11/testing-contracts.html seems to handle this pretty well, closing.
