### ISSUE TITLE
Unexpected return data

### ISSUE THREAD

**Issue by maurelian** [ethereum/vyper#915]
### Version Information

* vyper Version: 0.1.0b1

* OS: osx
* Python Version (python --version): 3.6.1
* Environment (output of `pip freeze`): 

### What's your issue about?

This is my contract: 

```python
@public 
def onERC721Received(_from: address ,_tokenId: uint256, _data: bytes[164]) -> (bytes[4]):
    return '\xf0\xb9\xe5\xba'
```

I wasn't getting the response I'd expected when using in a test suite, so I ran the `deployedBytecode` with the geth packaged evm-cli. 

`$ evm --code 60003560... --input f0b9e5ba run`

The output is:

```
0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000004f0b9e5ba00000000000000000000000000000000000000000000000000000000
```

Whereas I would have expected 4 byte return value of f0b9efba.

**Comment by jacqueswww** [comment]
That is very strange,

```
~'00000000000000000000000000000000',~
 '00000000000000000000000000000020',
~ '00000000000000000000000000000000',~
 '00000000000000000000000000000004',
 'f0b9e5ba000000000000000000000000',
~ '00000000000000000000000000000000'~
]
```

**Comment by maurelian** [comment]
My issue was fixed by changing the source code to return bytes32.  

```python
@public 
def onERC721Received(_operator: address, _from: address ,_tokenId: uint256, _data: bytes[1028]) -> bytes32:
  return 0xf0b9e5ba00000000000000000000000000000000000000000000000000000000
```

I admit it's not quite clear to me why. When I know the diff between bytes32 and bytes[32] I will have reached nirvana.

**Comment by fubuloubu** [comment]
`len(bytes[32])` is 33 (includes 1 byte for the length of the byte array)
`len(bytes32)` is 32 (hardcoded 32 byte [uint256] value)

**Comment by jacqueswww** [comment]
@fubuloubu actually that is incorrect, it's 64 bytes to encode a byte array (because of the 32 byte word size).

@maurelian With ABI encoding of a bytearray - with dynamic length (`bytes[x]` in vyper).
Each argument of the ABI is placed after each other in 32byte words.
- The first word 0x0.....20 (32 in decimal) -> points to the offset from the beginning of the whole encoding where the dynamic section starts.
- The second word starts at the 32 byte marker (after 1 argument). It's value is 0x0000....04 to indicate the bytearray is length of 4, starting at the next boundary.
- The third word contains the 4 necessary bytes, but this data has to be packed `ceil32()` -> giving you another word.

See this example http://solidity.readthedocs.io/en/v0.4.21/abi-spec.html#use-of-dynamic-types

For static types like `bytes4` / `bytes32` / `bytes128` there is no length word. Therefore you know that the bytes are simply stored in a size of `ceil32(len(x))` where `x ` is the part of `bytes`.

**Comment by maurelian** [comment]
>  with dynamic length (bytes[x] in vyper or bytes in solidity).

That part does the most to clarify. What confused me was not realizing that `bytes[x]` is a fixed length version of `bytes`. I was trying to see it as kind of an analog to bytesx (ie. bytes4, or bytes64). 

> Therefore you know that the bytes are simply stored in a size of `ceil32(len(x))` where x is the part of bytes.


I don't really know what `ceil32()` does, is it like `mod`? Also, wouldn't it simply be:

> the bytes are simply stored in a size of `x` where x is the part of bytes.

Or perhaps you're defining size as "number of words" not "number of bytes"? Is that a convention?
